version: '3.8'

services:
  # TimescaleDB Database
  timescaledb:
    image: timescale/timescaledb:latest-pg15
    container_name: alphapulse_timescaledb
    environment:
      POSTGRES_DB: ${TIMESCALEDB_DATABASE:-alphapulse}
      POSTGRES_USER: ${TIMESCALEDB_USERNAME:-alphapulse_user}
      POSTGRES_PASSWORD: ${TIMESCALEDB_PASSWORD:-alphapulse_password}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5432:5432"
    volumes:
      - timescaledb_data:/var/lib/postgresql/data
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${TIMESCALEDB_USERNAME:-alphapulse_user} -d ${TIMESCALEDB_DATABASE:-alphapulse}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # AlphaPulse Dashboard
  dashboard:
    build: .
    container_name: alphapulse_dashboard
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL:-postgresql://${TIMESCALEDB_USERNAME:-alphapulse_user}:${TIMESCALEDB_PASSWORD:-alphapulse_password}@timescaledb:5432/${TIMESCALEDB_DATABASE:-alphapulse}}
      - DASHBOARD_HOST=${DASHBOARD_HOST:-0.0.0.0}
      - DASHBOARD_PORT=${DASHBOARD_PORT:-8000}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - DEBUG=${DEBUG:-false}
      - APP_ENV=${APP_ENV:-production}
    volumes:
      - ./static:/app/static
      - ./logs:/app/logs
    depends_on:
      timescaledb:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  # Nginx Reverse Proxy (Optional)
  nginx:
    image: nginx:alpine
    container_name: alphapulse_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - dashboard
    restart: unless-stopped

  # Redis for Caching (Optional)
  redis:
    image: redis:7-alpine
    container_name: alphapulse_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped

volumes:
  timescaledb_data:
    driver: local
  redis_data:
    driver: local

networks:
  default:
    name: alphapulse_network
