# AlphaPulse Symbol Management Configuration
# Orchestration settings for 100-symbol scaled system

symbol_management:
  # Total symbols to track
  total_symbols: 100
  
  # Split between futures and spot
  futures_count: 50
  spot_count: 50
  
  # Symbol list update frequency
  update_interval_hours: 24  # Daily refresh
  
  # Minimum volume threshold (USD)
  min_volume_24h: 1000000  # $1M minimum daily volume
  
  # Symbol rotation settings
  rotation_enabled: true
  rotation_check_hours: 24
  
  # Excluded symbols (optional blacklist)
  excluded_symbols: []

websocket:
  # WebSocket connection settings
  max_connections: 2  # 1 connection = 200 streams, so 2 = 400 streams capacity
  streams_per_connection: 100
  
  # Connection health
  reconnect_delay_seconds: 5
  max_reconnect_attempts: 10
  ping_interval_seconds: 20
  
  # Performance mode
  performance_mode: "balanced"  # Options: "ultra_low_latency", "balanced", "conservative"

data_collection:
  # Primary data collection
  primary_timeframe: "1m"  # Collect via WebSocket
  
  # Derived timeframes (auto-generated by TimescaleDB)
  derived_timeframes:
    - "5m"
    - "15m"
    - "1h"
    - "4h"
    - "1d"
  
  # Buffer settings
  buffer_size_per_symbol: 200  # Keep last 200 candles in memory
  redis_ttl_seconds: 300  # 5 minutes cache
  
  # Batch processing
  batch_size: 100  # Insert 100 rows at once
  batch_flush_interval_seconds: 5  # Flush every 5 seconds

signal_generation:
  # Parallel analysis settings
  symbols_per_batch: 10  # Analyze 10 symbols in parallel
  analysis_interval_seconds: 60  # Run every minute
  
  # Complete cycle timing
  # 100 symbols รท 10 per batch = 10 batches
  # 10 batches ร 60 seconds = 10 minutes per complete cycle
  
  # Data requirements
  min_data_candles: 200  # Need 200 candles before analysis
  min_data_age_minutes: 210  # Need 3.5 hours of 1m data
  
  # Performance tuning
  max_concurrent_analyses: 20  # Maximum parallel model head executions
  analysis_timeout_seconds: 30  # Timeout per symbol analysis

database:
  # Connection pool settings
  min_pool_size: 10  # Increased for 100 symbols
  max_pool_size: 30  # Increased capacity
  
  # Query timeouts
  query_timeout_seconds: 60
  
  # Batch insert settings
  max_batch_size: 1000
  batch_timeout_seconds: 10

monitoring:
  # Metrics collection
  metrics_update_interval_seconds: 30
  
  # Performance alerts
  alert_on_low_throughput: true
  min_messages_per_second: 50  # Alert if below 50 msg/s
  
  # Health checks
  health_check_interval_seconds: 60

caching:
  # Multi-level cache settings
  l1_cache_size: 1000  # L1: Ultra-fast in-memory
  l1_ttl_seconds: 60
  
  l2_cache_size: 5000  # L2: Redis
  l2_ttl_seconds: 300
  
  # Cache warming
  warm_cache_on_startup: true

logging:
  # Log levels by component
  symbol_manager: "INFO"
  websocket_orchestrator: "INFO"
  signal_scheduler: "INFO"
  data_pipeline: "DEBUG"
  
  # Performance logging
  log_slow_operations: true
  slow_operation_threshold_ms: 500

