# Grafana Datasource Configuration for AlphaPlus
# Production monitoring setup

apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      httpMethod: POST
      queryTimeout: 60s
      timeInterval: 5s

  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    database: alphapulse
    user: alphapulse_monitor
    secureJsonData:
      password: secure_monitor_password
    jsonData:
      sslmode: disable
      maxOpenConns: 100
      maxIdleConns: 100
      connMaxLifetime: 14400

  - name: Redis
    type: redis-datasource
    access: proxy
    url: redis://redis-master:6379
    isDefault: false
    editable: true
    jsonData:
      client: standalone
      timeout: 10s
      pingInterval: 30s

  - name: AlphaPlus Trading Metrics
    type: prometheus
    access: proxy
    url: http://backend:8000
    isDefault: false
    editable: true
    jsonData:
      httpMethod: POST
      queryTimeout: 30s
      timeInterval: 1s
