apiVersion: v1
kind: Namespace
metadata:
  name: alphapulse
  labels:
    name: alphapulse
    environment: production
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: alphapulse-quota
  namespace: alphapulse
spec:
  hard:
    requests.cpu: "8"
    requests.memory: 16Gi
    limits.cpu: "16"
    limits.memory: 32Gi
    persistentvolumeclaims: "10"
    services: "20"
    pods: "20"
