global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'alphapulse'
    environment: 'production'

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # AlphaPulse Backend Metrics
  - job_name: 'alphapulse-backend'
    static_configs:
      - targets: ['alphapulse-backend:8000']
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 10s
    honor_labels: true
    scheme: http
    
  # AlphaPulse Dashboard Metrics
  - job_name: 'alphapulse-dashboard'
    static_configs:
      - targets: ['alphapulse-backend:8050']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 10s
    honor_labels: true
    scheme: http
    
  # AlphaPulse Frontend Metrics
  - job_name: 'alphapulse-frontend'
    static_configs:
      - targets: ['alphapulse-frontend:80']
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 10s
    honor_labels: true
    scheme: http
    
  # PostgreSQL Metrics
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s
    honor_labels: true
    scheme: http
    
  # Redis Metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s
    honor_labels: true
    scheme: http
    
  # Nginx Metrics
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']
    metrics_path: '/nginx_status'
    scrape_interval: 15s
    scrape_timeout: 10s
    honor_labels: true
    scheme: http
    
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 15s
    scrape_timeout: 10s
    honor_labels: true
    scheme: http
