global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'alphapulse-backend'
    static_configs:
      - targets: ['alphapulse_backend:8000']
    metrics_path: '/api/v1/metrics'
    scrape_interval: 5s

  - job_name: 'alphapulse-postgres'
    static_configs:
      - targets: ['alphapulse_postgres:5432']

  - job_name: 'alphapulse-redis'
    static_configs:
      - targets: ['alphapulse_redis:6379']

  - job_name: 'alphapulse-frontend'
    static_configs:
      - targets: ['alphapulse_frontend:3000']
