groups:
  - name: alphapulse_trading_alerts
    rules:
      # Precision Alert - Alert if precision drops below threshold
      - alert: LowPrecision
        expr: alphapulse_precision < 0.6
        for: 5m
        labels:
          severity: warning
          team: trading
        annotations:
          summary: "Low trading precision detected"
          description: "Trading precision has dropped to {{ $value | humanizePercentage }} for the last 5 minutes"
          dashboard: "AlphaPulse Trading Bot Dashboard"

      # Win Rate Alert - Alert if win rate drops below threshold
      - alert: LowWinRate
        expr: alphapulse_win_rate < 0.5
        for: 10m
        labels:
          severity: warning
          team: trading
        annotations:
          summary: "Low win rate detected"
          description: "Win rate has dropped to {{ $value | humanizePercentage }} for the last 10 minutes"
          dashboard: "AlphaPulse Trading Bot Dashboard"

      # Profit Factor Alert - Alert if profit factor drops below threshold
      - alert: LowProfitFactor
        expr: alphapulse_profit_factor < 1.2
        for: 15m
        labels:
          severity: warning
          team: trading
        annotations:
          summary: "Low profit factor detected"
          description: "Profit factor has dropped to {{ $value }} for the last 15 minutes"
          dashboard: "AlphaPulse Trading Bot Dashboard"

      # Average R/R Alert - Alert if average risk/reward drops below threshold
      - alert: LowAvgRR
        expr: alphapulse_avg_rr < 1.5
        for: 10m
        labels:
          severity: warning
          team: trading
        annotations:
          summary: "Low average risk/reward ratio detected"
          description: "Average R/R has dropped to {{ $value }} for the last 10 minutes"
          dashboard: "AlphaPulse Trading Bot Dashboard"

  - name: alphapulse_drift_alerts
    rules:
      # PSI Drift Alert - Alert if PSI drift score exceeds threshold
      - alert: HighPSIDrift
        expr: alphapulse_psi_drift_score > 0.25
        for: 5m
        labels:
          severity: critical
          team: ml
        annotations:
          summary: "High PSI drift detected"
          description: "PSI drift score has increased to {{ $value }} for the last 5 minutes"
          dashboard: "AlphaPulse Trading Bot Dashboard"

      # AUC Delta Alert - Alert if AUC delta exceeds threshold
      - alert: HighAUCDelta
        expr: alphapulse_auc_delta > 0.1
        for: 5m
        labels:
          severity: critical
          team: ml
        annotations:
          summary: "High AUC delta detected"
          description: "AUC delta has increased to {{ $value }} for the last 5 minutes"
          dashboard: "AlphaPulse Trading Bot Dashboard"

      # Concept Drift Alert - Alert if concept drift score exceeds threshold
      - alert: HighConceptDrift
        expr: alphapulse_concept_drift_score > 0.25
        for: 5m
        labels:
          severity: critical
          team: ml
        annotations:
          summary: "High concept drift detected"
          description: "Concept drift score has increased to {{ $value }} for the last 5 minutes"
          dashboard: "AlphaPulse Trading Bot Dashboard"

  - name: alphapulse_latency_alerts
    rules:
      # p95 Latency Alert - Alert if p95 latency exceeds threshold
      - alert: HighP95Latency
        expr: histogram_quantile(0.95, rate(alphapulse_inference_duration_seconds_bucket[5m])) > 0.5
        for: 2m
        labels:
          severity: warning
          team: infrastructure
        annotations:
          summary: "High p95 inference latency detected"
          description: "p95 inference latency has increased to {{ $value }}s for the last 2 minutes"
          dashboard: "AlphaPulse Trading Bot Dashboard"

      # p99 Latency Alert - Alert if p99 latency exceeds threshold
      - alert: HighP99Latency
        expr: histogram_quantile(0.99, rate(alphapulse_inference_duration_seconds_bucket[5m])) > 1.0
        for: 2m
        labels:
          severity: critical
          team: infrastructure
        annotations:
          summary: "High p99 inference latency detected"
          description: "p99 inference latency has increased to {{ $value }}s for the last 2 minutes"
          dashboard: "AlphaPulse Trading Bot Dashboard"

  - name: alphapulse_system_alerts
    rules:
      # CPU Usage Alert - Alert if CPU usage exceeds threshold
      - alert: HighCPUUsage
        expr: alphapulse_system_cpu_usage > 80
        for: 5m
        labels:
          severity: warning
          team: infrastructure
        annotations:
          summary: "High CPU usage detected"
          description: "CPU usage has increased to {{ $value }}% for the last 5 minutes"
          dashboard: "AlphaPulse Trading Bot Dashboard"

      # Memory Usage Alert - Alert if memory usage exceeds threshold
      - alert: HighMemoryUsage
        expr: alphapulse_system_memory_usage > 85
        for: 5m
        labels:
          severity: warning
          team: infrastructure
        annotations:
          summary: "High memory usage detected"
          description: "Memory usage has increased to {{ $value }}% for the last 5 minutes"
          dashboard: "AlphaPulse Trading Bot Dashboard"

      # Disk Usage Alert - Alert if disk usage exceeds threshold
      - alert: HighDiskUsage
        expr: alphapulse_system_disk_usage > 90
        for: 5m
        labels:
          severity: critical
          team: infrastructure
        annotations:
          summary: "High disk usage detected"
          description: "Disk usage has increased to {{ $value }}% for the last 5 minutes"
          dashboard: "AlphaPulse Trading Bot Dashboard"

      # Database Health Alert - Alert if database health is poor
      - alert: DatabaseHealthPoor
        expr: alphapulse_database_connection_health < 0.8
        for: 2m
        labels:
          severity: critical
          team: infrastructure
        annotations:
          summary: "Database health is poor"
          description: "Database connection health has dropped to {{ $value }} for the last 2 minutes"
          dashboard: "AlphaPulse Trading Bot Dashboard"

  - name: alphapulse_active_learning_alerts
    rules:
      # Active Learning Queue Size Alert - Alert if queue is getting too large
      - alert: ActiveLearningQueueLarge
        expr: alphapulse_active_learning_pending_items > 100
        for: 10m
        labels:
          severity: warning
          team: ml
        annotations:
          summary: "Active learning queue is large"
          description: "Active learning queue has {{ $value }} pending items for the last 10 minutes"
          dashboard: "AlphaPulse Trading Bot Dashboard"

      # Active Learning Processing Rate Alert - Alert if processing is too slow
      - alert: ActiveLearningSlowProcessing
        expr: rate(alphapulse_active_learning_processed_items_total[10m]) < 0.1
        for: 5m
        labels:
          severity: warning
          team: ml
        annotations:
          summary: "Active learning processing is slow"
          description: "Active learning processing rate is {{ $value }} items/minute for the last 5 minutes"
          dashboard: "AlphaPulse Trading Bot Dashboard"

  - name: alphapulse_model_alerts
    rules:
      # Model Accuracy Alert - Alert if model accuracy drops below threshold
      - alert: LowModelAccuracy
        expr: alphapulse_model_accuracy < 0.7
        for: 10m
        labels:
          severity: critical
          team: ml
        annotations:
          summary: "Low model accuracy detected"
          description: "Model accuracy has dropped to {{ $value | humanizePercentage }} for the last 10 minutes"
          dashboard: "AlphaPulse Trading Bot Dashboard"

      # Model Training Failure Alert - Alert if model training fails
      - alert: ModelTrainingFailure
        expr: increase(alphapulse_model_training_failures_total[5m]) > 0
        labels:
          severity: critical
          team: ml
        annotations:
          summary: "Model training failure detected"
          description: "{{ $value }} model training failures in the last 5 minutes"
          dashboard: "AlphaPulse Trading Bot Dashboard"

  - name: alphapulse_trading_volume_alerts
    rules:
      # Signal Generation Rate Alert - Alert if signal generation is too low
      - alert: LowSignalGeneration
        expr: rate(alphapulse_signals_generated_total[10m]) < 0.1
        for: 5m
        labels:
          severity: warning
          team: trading
        annotations:
          summary: "Low signal generation rate detected"
          description: "Signal generation rate is {{ $value }} signals/minute for the last 5 minutes"
          dashboard: "AlphaPulse Trading Bot Dashboard"

      # Signal Rejection Rate Alert - Alert if signal rejection rate is too high
      - alert: HighSignalRejection
        expr: rate(alphapulse_signals_rejected_total[10m]) / rate(alphapulse_signals_generated_total[10m]) > 0.8
        for: 5m
        labels:
          severity: warning
          team: trading
        annotations:
          summary: "High signal rejection rate detected"
          description: "Signal rejection rate is {{ $value | humanizePercentage }} for the last 5 minutes"
          dashboard: "AlphaPulse Trading Bot Dashboard"

  - name: alphapulse_portfolio_alerts
    rules:
      # Portfolio Drawdown Alert - Alert if portfolio drawdown exceeds threshold
      - alert: HighPortfolioDrawdown
        expr: alphapulse_portfolio_drawdown < -0.1
        for: 5m
        labels:
          severity: critical
          team: trading
        annotations:
          summary: "High portfolio drawdown detected"
          description: "Portfolio drawdown has reached {{ $value | humanizePercentage }} for the last 5 minutes"
          dashboard: "AlphaPulse Trading Bot Dashboard"

      # Portfolio P&L Alert - Alert if portfolio P&L is significantly negative
      - alert: NegativePortfolioPnL
        expr: alphapulse_portfolio_pnl < -1000
        for: 10m
        labels:
          severity: warning
          team: trading
        annotations:
          summary: "Negative portfolio P&L detected"
          description: "Portfolio P&L is ${{ $value }} for the last 10 minutes"
          dashboard: "AlphaPulse Trading Bot Dashboard"
